global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kicktalk-monitor'

rule_files:
  # Add alerting rules here if needed
  # - "rules/*.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OTEL Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  # Scrape KickTalk application metrics (when implemented)
  - job_name: 'kicktalk-app'
    static_configs:
      - targets: ['192.168.1.50:9464']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Scrape Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s

  # Redis metrics (if redis exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']